/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as errors from "../../../../errors";
import * as Brazebee from "../../..";
export declare class RateLimitError extends errors.BrazebeeError {
    constructor(body: Brazebee.ErrorResponse);
}
