/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "./environments";
import * as core from "./core";
import { Events } from "./api/resources/events/client/Client";
export declare namespace BrazebeeClient {
    interface Options {
        environment?: core.Supplier<environments.BrazebeeEnvironment | string>;
        apiKeyAuth: core.Supplier<string>;
    }
    interface RequestOptions {
        timeoutInSeconds?: number;
        maxRetries?: number;
    }
}
export declare class BrazebeeClient {
    protected readonly _options: BrazebeeClient.Options;
    constructor(_options: BrazebeeClient.Options);
    protected _events: Events | undefined;
    get events(): Events;
}
