"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BrazebeeClient = void 0;
const Client_1 = require("./api/resources/events/client/Client");
class BrazebeeClient {
    constructor(_options) {
        this._options = _options;
    }
    get events() {
        var _a;
        return ((_a = this._events) !== null && _a !== void 0 ? _a : (this._events = new Client_1.Events(this._options)));
    }
}
exports.BrazebeeClient = BrazebeeClient;
