/**
 * This file was auto-generated by Fern from our API Definition.
 */
export declare const BrazebeeEnvironment: {
    readonly Production: "https://api.brazebee.com";
};
export declare type BrazebeeEnvironment = typeof BrazebeeEnvironment.Production;
