"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.BrazebeeEnvironment = void 0;
exports.BrazebeeEnvironment = {
    Production: "https://api.brazebee.com",
};
