/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Company information. The company will be created if it doesn't exist, or updated with new data.
 *
 * Payment Provider Fields:
 * - payment_provider and payment_provider_id are automatically stored in the company record
 * - No manual mapping needed - pass them in your events and they'll be available in the dashboard
 * - Supports: Stripe, Paddle, Chargebee, or custom values
 *
 * CRM Provider Fields:
 * - crm_provider and crm_provider_id are automatically stored in the company record
 * - Enables easy synchronization with your CRM without manual mapping
 * - Supports: Salesforce, HubSpot, Pipedrive, or custom values
 *
 * Additional Fields:
 * You can include any custom fields which will be stored in the company record:
 * industry, size, plan, mrr, signup_date, location, etc.
 */
export interface CompanyInfo {
    /** Unique identifier for the company in your system */
    id: string;
    /** Company name */
    name: string;
    /**
     * Payment provider used by this company (e.g., 'stripe', 'paddle', 'chargebee').
     * This field is automatically stored and can be used for segmentation and analytics.
     */
    paymentProvider?: string;
    /**
     * Customer ID in the payment provider system (e.g., Stripe customer ID 'cus_abc123').
     * This field is automatically stored and linked to the company for easy identification.
     */
    paymentProviderId?: string;
    /**
     * CRM system used to manage this company (e.g., 'salesforce', 'hubspot', 'pipedrive').
     * This field is automatically stored and can be used for segmentation and analytics.
     */
    crmProvider?: string;
    /**
     * Account/Company ID in the CRM system (e.g., Salesforce Account ID, HubSpot Company ID).
     * This field is automatically stored and linked to the company for easy CRM synchronization.
     */
    crmProviderId?: string;
}
