/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Error response
 */
export interface ErrorResponse {
    /** Human-readable error message */
    error: string;
    /** Machine-readable error code */
    code?: string;
    /** Additional error details */
    details?: Record<string, unknown>;
}
