/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as Brazebee from "../../..";
/**
 * Request to track a customer journey event
 */
export interface TrackEventRequest {
    /** Company information */
    company: Brazebee.CompanyInfo;
    /** User information (optional for system events) */
    user?: Brazebee.UserInfo;
    /**
     * Event key matching a configured event setting. Common examples:
     * - onboarding_started, onboarding_completed
     * - home_viewed, dashboard_viewed
     * - feature_action_completed
     * - plan_upgraded, plan_downgraded
     */
    eventKey: string;
    /** Event-specific data and properties */
    data?: Record<string, unknown>;
    /** Event timestamp in ISO 8601 format. Defaults to current time if not provided. */
    timestamp?: Date;
}
