/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Response after successfully tracking an event
 */
export interface TrackEventResponse {
    /** Whether the event was successfully tracked */
    success: boolean;
    /** The event key that was tracked */
    eventKey: string;
    /** Timestamp when the event was accepted by Brazebee */
    acceptedAt: Date;
}
