/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * User information. Optional for system events.
 *
 * **Naming Options:**
 * - Provide `name` if you have the full name
 * - Provide `first_name` and `last_name` if you have separated names
 * - Or provide all three for maximum flexibility
 *
 * **Additional Fields:**
 * You can include any custom fields: role, plan, signup_date, last_login, etc.
 */
export interface UserInfo {
    /** Unique identifier for the user in your system */
    id: string;
    /** User email address */
    email?: string;
    /** User full name (e.g., "John Doe") */
    name?: string;
    /** User first name (e.g., "John") */
    firstName?: string;
    /** User last name (e.g., "Doe") */
    lastName?: string;
}
