/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as environments from "../../../../environments";
import * as core from "../../../../core";
import * as Brazebee from "../../..";
export declare namespace Events {
    interface Options {
        environment?: core.Supplier<environments.BrazebeeEnvironment | string>;
        apiKeyAuth: core.Supplier<string>;
    }
    interface RequestOptions {
        timeoutInSeconds?: number;
        maxRetries?: number;
    }
}
export declare class Events {
    protected readonly _options: Events.Options;
    constructor(_options: Events.Options);
    /**
     * Track a customer journey event. Events are automatically linked to companies and users,
     * creating them if they don't exist.
     *
     * **Common use cases:**
     * - Track onboarding progress (e.g., "Onboarding Started", "Setup Completed")
     * - Monitor feature adoption (e.g., "Dashboard Viewed", "Report Generated")
     * - Detect expansion signals (e.g., "User Limit Reached", "Plan Upgraded")
     * - Identify churn risks (e.g., "Cancel Viewed", "Cancel Started")
     * @throws {@link Brazebee.BadRequestError}
     * @throws {@link Brazebee.UnauthorizedError}
     * @throws {@link Brazebee.NotFoundError}
     * @throws {@link Brazebee.RateLimitError}
     * @throws {@link Brazebee.InternalServerError}
     *
     * @example
     *     await brazebee.events.track({
     *         company: {
     *             id: "acme_corp",
     *             name: "Acme Corporation",
     *             paymentProvider: "stripe",
     *             paymentProviderId: "cus_abc123"
     *         },
     *         user: {
     *             id: "user_123",
     *             email: "john@acme.com",
     *             firstName: "John",
     *             lastName: "Doe"
     *         },
     *         eventKey: "onboarding_completed",
     *         data: {
     *             "steps_completed": 5,
     *             "time_taken_seconds": 180
     *         },
     *         timestamp: new Date("2024-01-15T10:30:00.000Z")
     *     })
     *
     * @example
     *     await brazebee.events.track({
     *         company: {
     *             id: "acme_corp",
     *             name: "Acme Corporation"
     *         },
     *         user: {
     *             id: "user_123",
     *             email: "john@acme.com",
     *             firstName: "John",
     *             lastName: "Doe"
     *         },
     *         eventKey: "feature_action_completed",
     *         data: {
     *             "feature_name": "export",
     *             "export_format": "csv",
     *             "rows_exported": 1500
     *         }
     *     })
     *
     * @example
     *     await brazebee.events.track({
     *         company: {
     *             id: "acme_corp",
     *             name: "Acme Corporation"
     *         },
     *         eventKey: "plan_upgraded",
     *         data: {
     *             "from_plan": "starter",
     *             "to_plan": "professional",
     *             "mrr": 99
     *         }
     *     })
     */
    track(request: Brazebee.TrackEventRequest, requestOptions?: Events.RequestOptions): Promise<Brazebee.TrackEventResponse>;
}
