/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as Brazebee from "../../../../api";
import * as core from "../../../../core";
export declare const CompanyInfo: core.serialization.ObjectSchema<serializers.CompanyInfo.Raw, Brazebee.CompanyInfo>;
export declare namespace CompanyInfo {
    interface Raw {
        id: string;
        name: string;
        payment_provider?: string | null;
        payment_provider_id?: string | null;
        crm_provider?: string | null;
        crm_provider_id?: string | null;
    }
}
