/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as Brazebee from "../../../../api";
import * as core from "../../../../core";
export declare const ErrorResponse: core.serialization.ObjectSchema<serializers.ErrorResponse.Raw, Brazebee.ErrorResponse>;
export declare namespace ErrorResponse {
    interface Raw {
        error: string;
        code?: string | null;
        details?: Record<string, unknown> | null;
    }
}
