/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as Brazebee from "../../../../api";
import * as core from "../../../../core";
export declare const TrackEventResponse: core.serialization.ObjectSchema<serializers.TrackEventResponse.Raw, Brazebee.TrackEventResponse>;
export declare namespace TrackEventResponse {
    interface Raw {
        success: boolean;
        event_key: string;
        accepted_at: string;
    }
}
