/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as Brazebee from "../../../../api";
import * as core from "../../../../core";
export declare const TrackEventRequest: core.serialization.ObjectSchema<serializers.TrackEventRequest.Raw, Brazebee.TrackEventRequest>;
export declare namespace TrackEventRequest {
    interface Raw {
        company: serializers.CompanyInfo.Raw;
        user?: serializers.UserInfo.Raw | null;
        event_key: string;
        data?: Record<string, unknown> | null;
        timestamp?: string | null;
    }
}
