/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as Brazebee from "../../../../api";
import * as core from "../../../../core";
export declare const UserInfo: core.serialization.ObjectSchema<serializers.UserInfo.Raw, Brazebee.UserInfo>;
export declare namespace UserInfo {
    interface Raw {
        id: string;
        email?: string | null;
        name?: string | null;
        first_name?: string | null;
        last_name?: string | null;
    }
}
